- name: Create resource group
  hosts: localhost
  tasks:
   - name: Create a resource group
     azure_rm_resourcegroup:
       resource_group: "{{ resource_group }}"
       location: EastAsia
     register: rg
   - name: print the details
     debug:
       var: rg
      
