- name: Create resource group
  hosts: localhost
  vars:
    resource_gp: rg-ram
  tasks:
   - name: Create a resource group
     azure_rm_resourcegroup:
       resource_group: "{{ resource_gp }}"
       location: EastAsia
     register: rg
   - name: print the details
     debug:
       var: rg
      
