- name: Create resource group
  hosts: localhost
  tasks:
   - name: Create a resource group
     azure_rm_resourcegroup:
       name: myResourceGroup
       location: EastAsia
       tags:
         testing: testing
         delete: never
