- name: Create RG
  hosts: all
  vars:
    resource_gp: rg-ram
    location: eastasia
  tasks:
  
  - name: Create resource group
    azure_rm_resourcegroup:
      name: "{{ resource_gp }}"
      location: "{{ location }}"
    register: rg
  - debug:
      var: rg
